name: Build and deploy log-tailer
on:
  push:
    paths-ignore:
      - '*.md'

env:
  NAME: log-tailer

jobs:
  build_and_push:
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"
    permissions:
      contents: read
      id-token: write
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # ratchet:jdx/mise-action@v4
        with:
          version: 2025.12.12
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run checks
        run: mise check

      - uses: nais/platform-build-push-sign@a16d89d06262f12e3468a20b9cc70f5317290bab # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
